#
# ██╗  ██╗ █████╗ ██████╗      █████╗ ██████╗ ███╗   ███╗██╗███╗   ██╗    ████████╗ ██████╗  ██████╗ ██╗     ███████╗
# ██║ ██╔╝██╔══██╗██╔══██╗    ██╔══██╗██╔══██╗████╗ ████║██║████╗  ██║    ╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝
# █████╔╝ ███████║██████╔╝    ███████║██║  ██║██╔████╔██║██║██╔██╗ ██║       ██║   ██║   ██║██║   ██║██║     ███████╗
# ██╔═██╗ ██╔══██║██╔═══╝     ██╔══██║██║  ██║██║╚██╔╝██║██║██║╚██╗██║       ██║   ██║   ██║██║   ██║██║     ╚════██║
# ██║  ██╗██║  ██║██║         ██║  ██║██████╔╝██║ ╚═╝ ██║██║██║ ╚████║       ██║   ╚██████╔╝╚██████╔╝███████╗███████║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝         ╚═╝  ╚═╝╚═════╝ ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝       ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝
# by kap35

##################################
#                                #
#       CONFIGURATION PART       #
#                                #
##################################

config:
  use-database: false
  use-logs: false

database:
  host: localhost
  port: 3306
  database: database
  username: username
  password: password

logs:
  path: logs
  file-pattern-name: %date%_%time%.log
